### ISSUE TITLE
Possible defect in Hill Climbing Search or its Usage

### ISSUE THREAD

**Issue by GoogleCodeExporter** [aimacode/aima-java#81] opened 2015-03-12 21:47 UTC
```
Note from Gabriel Diaz:

"I'm not sure if this is a bug or not.
I'm doing an implementation of the BeamSearch using your code, and I noticed 
that when you run the N-Queens Application, for any number of queens, 
incremental and with Hill Climbing Search it ends immediately because the 
neighbour value is equal to the current value, so if at the HillClimbingSearch 
class, at the line 89, you let the comparison between the current and the 
neighbour value, just as minor, instead of minor or equal, the algorithm works.
am I right or am I missing something on the Hill Climbing Search definition?"


```

Original issue reported on code.google.com by `ctjoreilly@gmail.com` on 22 Aug 2013 at 1:44

**Comment by Chipe1** [comment] 2016-03-08 20:41
I don't think this should be marked as a bug. Hill Climbing search is meant to stop when there are no better neighbours. If we consider neighbour with value equal to the current node, we may end up in an infinite loop. I think Simulated-Annealing(Fig 4.5) would be better for N-Queens.

**Comment by ctjoreilly** [comment] 2016-03-08 20:43
:)

**Comment by smsubham** [comment] 2016-03-09 18:05
Its not a bug , According to basic principle of principle our search should stop when when no neighbor is better than current node(including equal to). Few years ago an algorithm called Tuned
Hybrid Imperialist Competitive Algorithm which is a modified form of Simulated-Annealing was used to solve this problem,

**Comment by ctjoreilly** [comment] 2016-03-09 22:13
Agreeing with feedback, this is not a bug.

**Closed by ctjoreilly** 2016-03-09 22:13 UTC
Labels: AIMA3e, AIMA4e, question
